#!/usr/bin/env python3
#
# Cross-build Vulkan CTS for Raspberry Pi 5's Broadcom V3D 7.x GPU and Mesa's
# v3dv Vulkan driver.
#
# Typical local build and sync:
#
#   scripts/cross_build_for_pi5_v3dv.py --sync pi5:~/
#
# This builds the Vulkan CTS executable target `deqp-vk`, stages it under:
#
#   build-rpi5-v3dv-debug/rpi5_v3dv_cts_debug/
#
# and rsyncs that directory to the remote Pi as:
#
#   ~/rpi5_v3dv_cts_debug/
#
# The generated `run-pi5-v3dv.sh` wrapper expects Mesa's Pi 5 v3dv build to
# have been synced to the Pi first. By default it looks for the debug Mesa
# prefix created by Mesa's cross_build_for_pi_5.py script:
#
#   ~/rpi5_v3dv_debug/
#
# For a release CTS build, this script defaults to:
#
#   ~/rpi5_v3dv/
#
# Override that on the Pi at runtime with `MESA_PREFIX` if needed.
#
# Useful commands on the Pi after syncing:
#
#   cd ~/rpi5_v3dv_cts_debug
#   ./run-pi5-v3dv.sh --deqp-case=dEQP-VK.info.device \
#       --deqp-log-filename=results-info-device.qpa
#
# A successful v3dv sanity run should report:
#
#   target implementation = 'Vulkan Headless'
#   Test case 'dEQP-VK.info.device'..
#     Pass (Not validated)
#
# The QPA log should identify the Broadcom GPU. For example:
#
#   grep -E 'deviceName|vendorID|apiVersion' results-info-device.qpa
#   # deviceName: V3D 7.1.7.0
#   # vendorID: 0x000014e4
#
# To run a case list from the synced mustpass data:
#
#   ./run-pi5-v3dv.sh --deqp-caselist-file=vk-default/info.txt \
#       --deqp-log-filename=results-info.qpa
#
# To force a different v3dv install prefix:
#
#   MESA_PREFIX=$HOME/rpi5_v3dv_debug ./run-pi5-v3dv.sh \
#       --deqp-case=dEQP-VK.info.device
#
import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SDK = Path.home() / "vulkansdk" / "1.4.328.1" / "aarch64"


def run(command, *, cwd=REPO_ROOT, env=None):
    print("+ " + " ".join(str(part) for part in command), flush=True)
    subprocess.run(command, cwd=cwd, env=env, check=True)


def make_env(sdk: Path):
    env = os.environ.copy()
    env.pop("PKG_CONFIG_PATH", None)

    pkg_dirs = [
        sdk / "share" / "pkgconfig",
        sdk / "lib" / "pkgconfig",
        Path("/usr/lib/aarch64-linux-gnu/pkgconfig"),
        Path("/usr/share/pkgconfig"),
    ]
    env["PKG_CONFIG_LIBDIR"] = os.pathsep.join(str(path) for path in pkg_dirs if path.exists())
    env["PKG_CONFIG_SYSROOT_DIR"] = ""
    return env


def write_toolchain(path: Path, sdk: Path, sysroot: Path | None):
    path.parent.mkdir(parents=True, exist_ok=True)

    find_roots = [sdk]
    if sysroot is not None:
        find_roots.insert(0, sysroot)

    root_lines = "\n".join(f'    "{root}"' for root in find_roots)
    sysroot_line = f'set(CMAKE_SYSROOT "{sysroot}")\n' if sysroot is not None else ""

    path.write_text(
        f"""# Generated by scripts/cross_build_for_pi5_v3dv.py.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_CROSSCOMPILING TRUE)
set(DE_CPU "DE_CPU_ARM_64")

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_AR aarch64-linux-gnu-gcc-ar)
set(CMAKE_RANLIB aarch64-linux-gnu-gcc-ranlib)
set(CMAKE_STRIP aarch64-linux-gnu-strip)
{sysroot_line}
set(CMAKE_FIND_ROOT_PATH
{root_lines}
)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(CMAKE_PREFIX_PATH "{sdk}")
link_directories("{sdk}/lib")
""",
        encoding="utf-8",
    )


def configure(build_dir: Path, toolchain: Path, build_type: str, generator: str, env):
    cmake_args = [
        "cmake",
        "-S",
        str(REPO_ROOT),
        "-B",
        str(build_dir),
        "-G",
        generator,
        f"-DCMAKE_TOOLCHAIN_FILE={toolchain}",
        f"-DCMAKE_BUILD_TYPE={build_type}",
        "-DDEQP_TARGET=vulkan_headless",
        "-DDEQP_DISABLE_VK_VIDEO_TESTS=ON",
        f"-DVULKANSC_PCUTIL_SRC_PATH={REPO_ROOT / 'external' / 'vulkansc-pcutil' / 'src'}",
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
    ]
    run(cmake_args, env=env)


def build(build_dir: Path, jobs: int, env):
    command = ["cmake", "--build", str(build_dir), "--target", "deqp-vk"]
    if jobs > 0:
        command.extend(["--", f"-j{jobs}"])
    run(command, env=env)


def copy_tree(src: Path, dst: Path):
    if not src.exists():
        return
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def stage(build_dir: Path, package_dir: Path, mesa_prefix: Path):
    module_dir = build_dir / "external" / "vulkancts" / "modules" / "vulkan"
    binary = module_dir / "deqp-vk"
    if not binary.exists():
        raise FileNotFoundError(f"Missing built binary: {binary}")

    package_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(binary, package_dir / "deqp-vk")
    copy_tree(module_dir / "vulkan", package_dir / "vulkan")
    copy_tree(module_dir / "vk-default", package_dir / "vk-default")

    runner = package_dir / "run-pi5-v3dv.sh"
    runner.write_text(
        f"""#!/bin/sh
set -eu
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MESA_PREFIX="${{MESA_PREFIX:-{mesa_prefix}}}"
ICD="$MESA_PREFIX/share/vulkan/icd.d/broadcom_icd.aarch64.json"

export LD_LIBRARY_PATH="$MESA_PREFIX/lib/aarch64-linux-gnu:$MESA_PREFIX/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
if [ -f "$ICD" ]; then
    export VK_ICD_FILENAMES="$ICD"
fi

cd "$HERE"
exec ./deqp-vk "$@"
""",
        encoding="utf-8",
    )
    runner.chmod(0o755)
    print(f"Staged Pi 5 CTS package at {package_dir}")


def sync_to_pi(package_dir: Path, remote: str):
    run(["rsync", "-avz", str(package_dir), remote])


def main():
    parser = argparse.ArgumentParser(description="Cross build Vulkan CTS deqp-vk for Raspberry Pi 5 v3dv.")
    parser.add_argument("-r", "--release", action="store_true", help="Use Release instead of Debug.")
    parser.add_argument("--build-dir", type=Path, help="Override the CMake build directory.")
    parser.add_argument("--package-dir", type=Path, help="Override the staged package directory.")
    parser.add_argument("--sdk", type=Path, default=DEFAULT_SDK, help="AArch64 Vulkan SDK prefix.")
    parser.add_argument("--mesa-prefix", type=Path, help="Mesa v3dv install prefix used on the Pi.")
    parser.add_argument("--sysroot", type=Path, help="Optional Raspberry Pi OS aarch64 sysroot.")
    parser.add_argument("--jobs", "-j", type=int, default=os.cpu_count() or 1, help="Parallel build jobs.")
    parser.add_argument("--generator", default="Ninja", help="CMake generator.")
    parser.add_argument("--configure-only", action="store_true", help="Stop after CMake configure.")
    parser.add_argument("--no-stage", action="store_true", help="Do not copy deqp-vk and data into package dir.")
    parser.add_argument("--sync", metavar="REMOTE", help='Rsync package dir, for example "pi5:~/".')
    args = parser.parse_args()

    build_type = "Release" if args.release else "Debug"
    suffix = "release" if args.release else "debug"
    build_dir = args.build_dir or (REPO_ROOT / f"build-rpi5-v3dv-{suffix}")
    package_dir = args.package_dir or (build_dir / f"rpi5_v3dv_cts_{suffix}")
    mesa_prefix = args.mesa_prefix or (Path.home() / ("rpi5_v3dv" if args.release else "rpi5_v3dv_debug"))
    toolchain = build_dir / "pi5-aarch64-toolchain.cmake"

    if not shutil.which("aarch64-linux-gnu-gcc") or not shutil.which("aarch64-linux-gnu-g++"):
        sys.exit("Missing aarch64-linux-gnu GCC/G++ cross compiler in PATH.")
    if args.generator == "Ninja" and not shutil.which("ninja"):
        sys.exit("Missing ninja in PATH.")
    if not args.sdk.exists():
        sys.exit(f"AArch64 Vulkan SDK prefix does not exist: {args.sdk}")

    env = make_env(args.sdk)
    write_toolchain(toolchain, args.sdk, args.sysroot)
    configure(build_dir, toolchain, build_type, args.generator, env)
    if args.configure_only:
        return

    build(build_dir, args.jobs, env)
    if not args.no_stage:
        stage(build_dir, package_dir, mesa_prefix)
        if args.sync:
            sync_to_pi(package_dir, args.sync)


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as err:
        sys.exit(err.returncode)
